name: {{feature_name.snakeCase()}}
description: Starter {{feature_name.pascalCase()}} Feature
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  i69n: ^2.1.0
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
